// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/internal/database/sqlc"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateSession(ctx context.Context, sessionParams database.CreateSessionParams) (database.Session, error) {
	ret := _mock.Called(ctx, sessionParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 database.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.CreateSessionParams) (database.Session, error)); ok {
		return returnFunc(ctx, sessionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.CreateSessionParams) database.Session); ok {
		r0 = returnFunc(ctx, sessionParams)
	} else {
		r0 = ret.Get(0).(database.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.CreateSessionParams) error); ok {
		r1 = returnFunc(ctx, sessionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionParams database.CreateSessionParams
func (_e *MockRepository_Expecter) CreateSession(ctx interface{}, sessionParams interface{}) *MockRepository_CreateSession_Call {
	return &MockRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, sessionParams)}
}

func (_c *MockRepository_CreateSession_Call) Run(run func(ctx context.Context, sessionParams database.CreateSessionParams)) *MockRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.CreateSessionParams
		if args[1] != nil {
			arg1 = args[1].(database.CreateSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateSession_Call) Return(session database.Session, err error) *MockRepository_CreateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, sessionParams database.CreateSessionParams) (database.Session, error)) *MockRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}
