// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    user_id,
    password_hash,
    refresh_token,
    provider
) VALUES (
    $1, $2, $3, $4
)
RETURNING user_id, password_hash, refresh_token, provider
`

type CreateAccountParams struct {
	UserID       pgtype.UUID
	PasswordHash string
	RefreshToken pgtype.Text
	Provider     Providers
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.PasswordHash,
		arg.RefreshToken,
		arg.Provider,
	)
	var i Account
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.Provider,
	)
	return i, err
}
