// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
    user_id,
    password_hash,
    refresh_token,
    provider
) VALUES (
    $1, $2, $3, $4
)
`

type CreateAccountParams struct {
	UserID       pgtype.UUID
	PasswordHash string
	RefreshToken pgtype.Text
	Provider     Providers
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.UserID,
		arg.PasswordHash,
		arg.RefreshToken,
		arg.Provider,
	)
	return err
}
