// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Providers string

const (
	ProvidersLocal  Providers = "local"
	ProvidersGithub Providers = "github"
	ProvidersGoogle Providers = "google"
)

func (e *Providers) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Providers(s)
	case string:
		*e = Providers(s)
	default:
		return fmt.Errorf("unsupported scan type for Providers: %T", src)
	}
	return nil
}

type NullProviders struct {
	Providers Providers
	Valid     bool // Valid is true if Providers is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviders) Scan(value interface{}) error {
	if value == nil {
		ns.Providers, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Providers.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviders) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Providers), nil
}

type Roles string

const (
	RolesUser     Roles = "user"
	RolesAdmin    Roles = "admin"
	RolesTeamLead Roles = "team_lead"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type NullRoles struct {
	Roles Roles
	Valid bool // Valid is true if Roles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoles) Scan(value interface{}) error {
	if value == nil {
		ns.Roles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roles), nil
}

type SubscriptionPlans string

const (
	SubscriptionPlansFree       SubscriptionPlans = "Free"
	SubscriptionPlansPro        SubscriptionPlans = "Pro"
	SubscriptionPlansEnterprise SubscriptionPlans = "Enterprise"
)

func (e *SubscriptionPlans) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionPlans(s)
	case string:
		*e = SubscriptionPlans(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionPlans: %T", src)
	}
	return nil
}

type NullSubscriptionPlans struct {
	SubscriptionPlans SubscriptionPlans
	Valid             bool // Valid is true if SubscriptionPlans is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionPlans) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionPlans, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionPlans.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionPlans) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionPlans), nil
}

type Account struct {
	UserID       pgtype.UUID
	PasswordHash string
	RefreshToken pgtype.Text
	Provider     Providers
}

type Post struct {
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Title       string
	Description string
	Tags        []string
	AuthorID    string
}

type Session struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
}

type User struct {
	UserID           pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Email            string
	EmailVerified    bool
	Name             string
	Avatar           pgtype.Text
	Role             Roles
	SubscriptionPlan SubscriptionPlans
}
