// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_responses.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPostResponse = `-- name: CreatePostResponse :one
INSERT INTO post_responses (
    post_id,
    user_id,
    message
) VALUES (
    $1, $2, $3
) RETURNING response_id, post_id, user_id, message, status, created_at, updated_at
`

type CreatePostResponseParams struct {
	PostID  pgtype.UUID
	UserID  pgtype.UUID
	Message string
}

type CreatePostResponseRow struct {
	ResponseID pgtype.UUID
	PostID     pgtype.UUID
	UserID     pgtype.UUID
	Message    string
	Status     StatusResponses
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreatePostResponse(ctx context.Context, arg CreatePostResponseParams) (CreatePostResponseRow, error) {
	row := q.db.QueryRow(ctx, createPostResponse, arg.PostID, arg.UserID, arg.Message)
	var i CreatePostResponseRow
	err := row.Scan(
		&i.ResponseID,
		&i.PostID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostResponses = `-- name: GetPostResponses :many
SELECT 
    r.response_id, 
    r.post_id, 
    r.user_id, 
    r.message, 
    r.status, 
    r.created_at, 
    r.updated_at,
    u.email,
    u.name,
    u.avatar
FROM post_responses r
JOIN users u ON u.user_id = r.user_id
WHERE r.post_id = $1
ORDER BY r.created_at DESC
`

type GetPostResponsesRow struct {
	ResponseID pgtype.UUID
	PostID     pgtype.UUID
	UserID     pgtype.UUID
	Message    string
	Status     StatusResponses
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Email      string
	Name       string
	Avatar     pgtype.Text
}

func (q *Queries) GetPostResponses(ctx context.Context, postID pgtype.UUID) ([]GetPostResponsesRow, error) {
	rows, err := q.db.Query(ctx, getPostResponses, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostResponsesRow
	for rows.Next() {
		var i GetPostResponsesRow
		if err := rows.Scan(
			&i.ResponseID,
			&i.PostID,
			&i.UserID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Name,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
