// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id,
    title,
    description,
    tags,
    author_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
) RETURNING id, created_at, updated_at, deleted_at, title, description, tags, author_id
`

type CreatePostParams struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Tags        []string
	AuthorID    string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.AuthorID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.AuthorID,
	)
	return i, err
}

const getAuthorPost = `-- name: GetAuthorPost :one
SELECT id, created_at, updated_at, deleted_at, title, description, tags, author_id FROM posts
WHERE author_id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAuthorPost(ctx context.Context, authorID string) (Post, error) {
	row := q.db.QueryRow(ctx, getAuthorPost, authorID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.AuthorID,
	)
	return i, err
}

const getPostById = `-- name: GetPostById :one
SELECT id, created_at, updated_at, deleted_at, title, description, tags, author_id FROM posts
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPostById(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.AuthorID,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    tags = COALESCE($3, tags),
    updated_at = NOW()
WHERE id = $4
RETURNING id, title, description, tags
`

type UpdatePostParams struct {
	Title       string
	Description string
	Tags        []string
	ID          pgtype.UUID
}

type UpdatePostRow struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Tags        []string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (UpdatePostRow, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.ID,
	)
	var i UpdatePostRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
	)
	return i, err
}
