// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id,
    title,
    description,
    tags,
    author_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
) RETURNING id, created_at, updated_at, deleted_at, title, description, tags, author_id
`

type CreatePostParams struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Tags        []string
	AuthorID    pgtype.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.AuthorID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.AuthorID,
	)
	return i, err
}

const getAuthorPost = `-- name: GetAuthorPost :one
SELECT id, created_at, updated_at, deleted_at, title, description, tags, author_id FROM posts
WHERE author_id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAuthorPost(ctx context.Context, authorID pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getAuthorPost, authorID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.AuthorID,
	)
	return i, err
}

const getPostById = `-- name: GetPostById :one
SELECT
    p.id,
    p.title,
    p.description,
    p.tags,
    COALESCE(NULLIF(u.name, ''), ('user-' || LEFT(p.author_id::text, 8)))::text AS author_name
FROM posts p
JOIN users u ON u.user_id = p.author_id
WHERE p.id = $1 AND p.deleted_at IS NULL
LIMIT 1
`

type GetPostByIdRow struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Tags        []string
	AuthorName  string
}

func (q *Queries) GetPostById(ctx context.Context, id pgtype.UUID) (GetPostByIdRow, error) {
	row := q.db.QueryRow(ctx, getPostById, id)
	var i GetPostByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.AuthorName,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT
    p.id,
    p.title,
    p.description,
    p.tags,
    COALESCE(NULLIF(u.name, ''), ('user-' || LEFT(p.author_id::text, 8)))::text AS author_name
FROM posts p
JOIN users u ON u.user_id = p.author_id
WHERE p.deleted_at IS NULL
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32
	Offset int32
}

type ListPostsRow struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Tags        []string
	AuthorName  string
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    tags = COALESCE($3, tags),
    updated_at = NOW()
WHERE id = $4
RETURNING id, title, description, tags
`

type UpdatePostParams struct {
	Title       string
	Description string
	Tags        []string
	ID          pgtype.UUID
}

type UpdatePostRow struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Tags        []string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (UpdatePostRow, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.ID,
	)
	var i UpdatePostRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
	)
	return i, err
}
