// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const creatSession = `-- name: CreatSession :one
INSERT INTO sessions (
    id,
    user_id,
    refresh_token,
    user_agent,
    client_ip,
    is_blocked,
    expires_at,
    created_at,
    revoked_at
) VALUES (
    $1, $2, $3, $4, $5, false, $6, NOW(), NOW()
) RETURNING id, user_id, refresh_token, expires_at, created_at, revoked_at, user_agent, client_ip, is_blocked
`

type CreatSessionParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	RefreshToken string
	UserAgent    string
	ClientIp     string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreatSession(ctx context.Context, arg CreatSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, creatSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
	)
	return i, err
}
