// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id,
    email,
    email_verifed,
    name,
    avatar,
    role,
    subscription_plan,
    created_at,
    updated_at
    ) VALUES (
    $1, $2, false, $3, $4, $5, $6, NOW(), NOW()
    )
    RETURNING user_id, created_at, updated_at, deleted_at, email, email_verifed, name, avatar, role, subscription_plan
`

type CreateUserParams struct {
	UserID           pgtype.UUID
	Email            string
	Name             string
	Avatar           pgtype.Text
	Role             Roles
	SubscriptionPlan SubscriptionPlans
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Email,
		arg.Name,
		arg.Avatar,
		arg.Role,
		arg.SubscriptionPlan,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.EmailVerifed,
		&i.Name,
		&i.Avatar,
		&i.Role,
		&i.SubscriptionPlan,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, created_at, updated_at, deleted_at, email, email_verifed, name, avatar, role, subscription_plan FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.EmailVerifed,
		&i.Name,
		&i.Avatar,
		&i.Role,
		&i.SubscriptionPlan,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, created_at, updated_at, deleted_at, email, email_verifed, name, avatar, role, subscription_plan FROM users
WHERE user_id = $1 AND deleted_at IS NULL 
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.EmailVerifed,
		&i.Name,
		&i.Avatar,
		&i.Role,
		&i.SubscriptionPlan,
	)
	return i, err
}
