// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/internal/database/sqlc"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetUserWithPasswordByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserWithPasswordByEmail(ctx context.Context, email string) (database.GetUserWithPasswordByEmailRow, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithPasswordByEmail")
	}

	var r0 database.GetUserWithPasswordByEmailRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (database.GetUserWithPasswordByEmailRow, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) database.GetUserWithPasswordByEmailRow); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(database.GetUserWithPasswordByEmailRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserWithPasswordByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithPasswordByEmail'
type MockRepository_GetUserWithPasswordByEmail_Call struct {
	*mock.Call
}

// GetUserWithPasswordByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetUserWithPasswordByEmail(ctx interface{}, email interface{}) *MockRepository_GetUserWithPasswordByEmail_Call {
	return &MockRepository_GetUserWithPasswordByEmail_Call{Call: _e.mock.On("GetUserWithPasswordByEmail", ctx, email)}
}

func (_c *MockRepository_GetUserWithPasswordByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetUserWithPasswordByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserWithPasswordByEmail_Call) Return(getUserWithPasswordByEmailRow database.GetUserWithPasswordByEmailRow, err error) *MockRepository_GetUserWithPasswordByEmail_Call {
	_c.Call.Return(getUserWithPasswordByEmailRow, err)
	return _c
}

func (_c *MockRepository_GetUserWithPasswordByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (database.GetUserWithPasswordByEmailRow, error)) *MockRepository_GetUserWithPasswordByEmail_Call {
	_c.Call.Return(run)
	return _c
}
