// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/internal/identity/application/dto"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionService creates a new instance of MockSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionService {
	mock := &MockSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionService is an autogenerated mock type for the SessionService type
type MockSessionService struct {
	mock.Mock
}

type MockSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionService) EXPECT() *MockSessionService_Expecter {
	return &MockSessionService_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionService
func (_mock *MockSessionService) CreateSession(ctx context.Context, request *dto.CreateSessionDTO) (*dto.SessionResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *dto.SessionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateSessionDTO) (*dto.SessionResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateSessionDTO) *dto.SessionResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SessionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CreateSessionDTO) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionService_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionService_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dto.CreateSessionDTO
func (_e *MockSessionService_Expecter) CreateSession(ctx interface{}, request interface{}) *MockSessionService_CreateSession_Call {
	return &MockSessionService_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, request)}
}

func (_c *MockSessionService_CreateSession_Call) Run(run func(ctx context.Context, request *dto.CreateSessionDTO)) *MockSessionService_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CreateSessionDTO
		if args[1] != nil {
			arg1 = args[1].(*dto.CreateSessionDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_CreateSession_Call) Return(sessionResponse *dto.SessionResponse, err error) *MockSessionService_CreateSession_Call {
	_c.Call.Return(sessionResponse, err)
	return _c
}

func (_c *MockSessionService_CreateSession_Call) RunAndReturn(run func(ctx context.Context, request *dto.CreateSessionDTO) (*dto.SessionResponse, error)) *MockSessionService_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}
